

spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: javers_audit_db
      username: javersuser
      password: bk2rFn*d

  jackson:
    default-property-inclusion: NON_NULL


# Enable Logging mongo queries
logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG


javers:
  documentDbCompatibilityEnabled: false
  objectAccessHook: org.javers.spring.mongodb.DBRefUnproxyObjectAccessHook
  snapshotsCacheSize: 5000
  snapshotCollectionName: "jv_snapshots"
  headCollectionName: "jv_head_id"
  schemaManagementEnabled: true